# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vonni_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import * 



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(385, 427)
        MainWindow.setStyleSheet("background-color: white")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progLabel = QtWidgets.QLabel(self.centralwidget)
        self.progLabel.setGeometry(QtCore.QRect(31, 16, 321, 45))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.progLabel.setFont(font)
        self.progLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.progLabel.setObjectName("progLabel")
        self.text_box = QtWidgets.QTextEdit(self.centralwidget)
        self.text_box.setGeometry(QtCore.QRect(31, 228, 331, 61))
        self.text_box.setObjectName("text_box")
        self.text_box.setStyleSheet("border: 1px solid black")
        self.check_botton = QtWidgets.QPushButton(self.centralwidget)
        self.check_botton.setGeometry(QtCore.QRect(30, 300, 331, 23))
        self.check_botton.setObjectName("check_botton")
        self.check_botton.setStyleSheet("border: 1px solid black")
        self.pic = QtWidgets.QLabel(self.centralwidget)
        self.pic.setGeometry(QtCore.QRect(31, 67, 329, 155))
        self.pic.setText("")
        self.pic.setPixmap(QtGui.QPixmap("F:\Study\Quarter 1\Знакомство с языком Python\Seminars\Урок 7. Функции высшего порядка\hw_task1/vonni.png"))
        self.pic.setObjectName("pic")
        self.answer = QtWidgets.QLabel(self.centralwidget)
        self.answer.setGeometry(QtCore.QRect(30, 339, 331, 41))
        self.answer.setText("")
        self.answer.setObjectName("answer")
        self.answer.setFont(QFont('Times',18))
        self.answer.setAlignment(QtCore.Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 385, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.progLabel.setText(_translate("MainWindow", "Проверка рифмы"))
        self.text_box.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.check_botton.setText(_translate("MainWindow", "Проверить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
